### ISSUE TITLE
Error while importing project

### ISSUE THREAD

**Issue by alxsimo** [nmoskalenko/rxFirebase#18]
Want to add some stuff but when importing and building the project I'm getting this build error:

![image](https://cloud.githubusercontent.com/assets/579465/19467416/612a2750-9511-11e6-9d37-583965a0e933.png)

`Error:(26, 28) No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').``

Any clues about this?

**Comment by nmoskalenko** [comment]
This is an old Google Play Services issue, http://stackoverflow.com/questions/19843784/google-play-services-library-update-and-missing-symbol-integer-google-play-serv
