### ISSUE TITLE
Change thread

### ISSUE THREAD

**Issue by marcohc** [nmoskalenko/rxFirebase#20]
Hi @nmoskalenko and all contributors, thanks for this handy library, I was looking for something like that.

My main issue working with Firebase is that the return calls are always in the main thread, unless you do this workaround using a thread executor (https://firebase.googleblog.com/2016/10/become-a-firebase-taskmaster-part-4.html, see all the parts)

So my point is, is there a way to use your library an use the threads defined in a subscription of Rx instead of returning to the main thread?

Thanks!

**Comment by MehdiChouag** [comment]
Hi @nmoskalenko,
I'm currently facing the same issue as @marcohc is there a workaround to execute operations in an other thread ?

Thanks

**Comment by nmoskalenko** [comment]
Hello @marcohc , @MehdiChouag ! Thanks for feedback.
I'm not sure that I totally understand your problem, but let me summary what I understand here.
Firebase DO callback all the data events in Main Thread by its own architecture. So, according to this, RxFirebase do data mapping in UI thread as well. 
But then, you can always observe your data in any thread you want using RxJava techniques, specifying .observeOn(Schedulers.xxx()) or any other Scheduler.
Does it fits your needs? Or you want to make data mapping also in non-main thread?

**Comment by borysstach** [comment]
I think it's a good idea.
In my case change from:
```
RxFirebaseDatabase.observeValueEvent(reference, DataSnapshotMapper.listOf(clazz))
``` 
to

```
RxFirebaseDatabase.observeValueEvent(reference).observeOn(Schedulers.computation()).map(DataSnapshotMapper.listOf(clazz))
```
 speed up app like ten times.

**Comment by marcohc** [comment]
@nmoskalenko Thanks for the answer and sorry for the delay. The key as you said is use ´observeOn´ Rx method to redirect Firebase callback. 
I'm gonna close this issue, greetings from @antslava which is seated go my side :D Cheers
