### ISSUE TITLE
Switch to a non-static API

### ISSUE THREAD

**Issue by psh** [nmoskalenko/rxFirebase#25]
It would help our testing if there was a non-static API - it would allow mock instances of the ```RxFirebase*``` classes to be injected with Dagger while we are testing.

**Comment by nmoskalenko** [comment]
Hi @psh !
I don't think non-static API is good for such kind of helpers. IMO would just make is harder to consume.
To test your code you may mock firebase's DatabaseReference/DataSnapshot as I do for unit testing in this repo.
