### ISSUE TITLE
Java Server Version

### ISSUE THREAD

**Issue by ahaverty** [nmoskalenko/rxFirebase#4]
I've adapted your repository locally to work for Firebase Java Server (https://firebase.google.com/docs/server/setup)

When I say adapted, I've taken the core of your RxFirebaseDatabase and RxFirebaseChildEvent classes and essentially dropped them into a new project, removing any trace of android, also adding the above firebase server dependency from Google.

I want to share it similarly to this great repo, for anyone using Firebase server.
What would you recommend? It'd be great to be able to link the core functionality of this repo's RxDatabase, but I'm guessing a new repo would be best? Should I just upload my own, gradle it up, and maybe ask you to add a link to it in your readme?

Thanks again for making Firebase so much more usable!

**Comment by nmoskalenko** [comment]
@ahaverty , sure.
Please feel free to use the sources as you wish.
Setup the java server version repo and would couple them in readme's.

**Comment by ahaverty** [comment]
Thanks @nmoskalenko I'll get back to you on that!
